#!/bin/bash
#
# DESCRIPTION
#	Invoke developer build
#
# USAGE:
#	Steps to invoke this script.
#		export NLEXTERNALDIR2=<path>
#		export BUILD_NUMBER=<#>
#		source setEnv
#		./buildDev
#
# Jenkins BUILD:
#	cd $WORKSPACE
#	export NLEXTERNALDIR2=C:/Jenkins/jobs/source_main_external/workspace
#	source setEnv
#	./buildDev
#
# DEBUG:
#	To debug ANT problems, add -v option to an ANT command. For example:
#		$ANT -v -f scripts/build_xlib.xml


#
# Check for errors
#

if [ ! -d ./xlib ]
 then
	echo "### ERROR: Missing xlib directory ./xlib"
	exit 1
fi


#
# Compile
#

export ANT_HOME=$NLEXTERNALDIR2/apache-ant/apache-ant-1.7.0

ANT=$ANT_HOME/bin/ant
LOG_FILE=buildDev.log

(
set -x
# Prepare environment
./configure --type=dev || exit $?
source build.config

# Compile code and build installers
export ANT_OPTS="-Xmx1024M -XX:PermSize=128m -XX:MaxPermSize=512m"
export ANT_ARGS="-Dexternal.dir=$NLEXTERNALDIR2 -Dversion_str=$VERSION_STR -Dversion_build_short=$VERSION_BUILD_SHORT -Dbuild_date_long=$BUILD_DATE_LONG"
$ANT -f src/build.xml buildOnly || exit $?

set +x
) 2>&1 | tee $LOG_FILE

exit ${PIPESTATUS[0]}
