package com.nextlabs.rms.services.cxf.destiny.interfaces.log.v5;

import com.nextlabs.rms.services.cxf.destiny.services.ServiceNotReadyFault;
import com.nextlabs.rms.services.cxf.destiny.services.UnauthorizedCallerFault;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-07-13T15:37:52.197+08:00
 * Generated source version: 3.0.4
 *
 */
@WebService(targetNamespace = "http://nextlabs.com/destiny/interfaces/log/v5", name = "LogServiceIF")
@XmlSeeAlso({com.nextlabs.rms.services.cxf.destiny.types.log.v5.ObjectFactory.class, com.nextlabs.rms.services.cxf.destiny.types.log.v5.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface LogServiceIF {

    @WebResult(name = "response", targetNamespace = "http://nextlabs.com/destiny/interfaces/log/v5", partName = "response")
    @WebMethod
    public com.nextlabs.rms.services.cxf.destiny.types.log.v5.LogStatus logPolicyActivityV2(
            @WebParam(partName = "logs", name = "logs")
            java.lang.String logs
    ) throws ServiceNotReadyFault, UnauthorizedCallerFault;

    @WebResult(name = "response", targetNamespace = "http://nextlabs.com/destiny/interfaces/log/v5", partName = "response")
    @WebMethod
    public com.nextlabs.rms.services.cxf.destiny.types.log.v5.LogStatus logPolicyActivity(
            @WebParam(partName = "logs", name = "logs")
            java.lang.String logs
    ) throws ServiceNotReadyFault, UnauthorizedCallerFault;

    @WebResult(name = "response", targetNamespace = "http://nextlabs.com/destiny/interfaces/log/v5", partName = "response")
    @WebMethod
    public com.nextlabs.rms.services.cxf.destiny.types.log.v5.LogStatus logPolicyAssistant(
            @WebParam(partName = "logs", name = "logs")
            java.lang.String logs
    ) throws ServiceNotReadyFault, UnauthorizedCallerFault;

    @WebResult(name = "response", targetNamespace = "http://nextlabs.com/destiny/interfaces/log/v5", partName = "response")
    @WebMethod
    public com.nextlabs.rms.services.cxf.destiny.types.log.v5.LogStatus logTracking(
            @WebParam(partName = "logs", name = "logs")
            java.lang.String logs
    ) throws ServiceNotReadyFault, UnauthorizedCallerFault;

    @WebResult(name = "response", targetNamespace = "http://nextlabs.com/destiny/interfaces/log/v5", partName = "response")
    @WebMethod
    public com.nextlabs.rms.services.cxf.destiny.types.log.v5.LogStatus logTrackingV3(
            @WebParam(partName = "logs", name = "logs")
            java.lang.String logs
    ) throws ServiceNotReadyFault, UnauthorizedCallerFault;

    @WebResult(name = "response", targetNamespace = "http://nextlabs.com/destiny/interfaces/log/v5", partName = "response")
    @WebMethod
    public com.nextlabs.rms.services.cxf.destiny.types.log.v5.LogStatus logTrackingV2(
            @WebParam(partName = "logs", name = "logs")
            java.lang.String logs
    ) throws ServiceNotReadyFault, UnauthorizedCallerFault;

    @WebResult(name = "response", targetNamespace = "http://nextlabs.com/destiny/interfaces/log/v5", partName = "response")
    @WebMethod
    public com.nextlabs.rms.services.cxf.destiny.types.log.v5.LogStatus logPolicyActivityV3(
            @WebParam(partName = "logs", name = "logs")
            java.lang.String logs
    ) throws ServiceNotReadyFault, UnauthorizedCallerFault;

    @WebResult(name = "response", targetNamespace = "http://nextlabs.com/destiny/interfaces/log/v5", partName = "response")
    @WebMethod
    public com.nextlabs.rms.services.cxf.destiny.types.log.v3.LogStatus logPolicyActivityV5(
            @WebParam(partName = "logs", name = "logs")
            java.lang.String logs
    ) throws ServiceNotReadyFault, UnauthorizedCallerFault;
}