package com.nextlabs.rms.services.cxf.destiny.interfaces.log.v3;

import com.nextlabs.rms.services.cxf.destiny.services.ServiceNotReadyFault;
import com.nextlabs.rms.services.cxf.destiny.services.UnauthorizedCallerFault;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-20T18:06:18.119+08:00
 * Generated source version: 3.0.4
 *
 */
@WebService(targetNamespace = "http://nextlabs.com/destiny/interfaces/log/v3", name = "LogServiceIF")
@XmlSeeAlso({com.nextlabs.rms.services.cxf.destiny.types.log.v3.ObjectFactory.class, com.nextlabs.rms.services.cxf.destiny.types.log.v3.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface LogServiceIF {

    @WebResult(name = "response", targetNamespace = "http://nextlabs.com/destiny/interfaces/log/v3", partName = "response")
    @WebMethod
    public com.nextlabs.rms.services.cxf.destiny.types.log.v3.LogStatus logTrackingV2(
            @WebParam(partName = "logs", name = "logs")
            java.lang.String logs
    ) throws UnauthorizedCallerFault, ServiceNotReadyFault;

    @WebResult(name = "response", targetNamespace = "http://nextlabs.com/destiny/interfaces/log/v3", partName = "response")
    @WebMethod
    public com.nextlabs.rms.services.cxf.destiny.types.log.v3.LogStatus logPolicyActivityV3(
            @WebParam(partName = "logs", name = "logs")
            java.lang.String logs
    ) throws UnauthorizedCallerFault, ServiceNotReadyFault;

    @WebResult(name = "response", targetNamespace = "http://nextlabs.com/destiny/interfaces/log/v3", partName = "response")
    @WebMethod
    public com.nextlabs.rms.services.cxf.destiny.types.log.v3.LogStatus logPolicyActivity(
            @WebParam(partName = "logs", name = "logs")
            java.lang.String logs
    ) throws UnauthorizedCallerFault, ServiceNotReadyFault;

    @WebResult(name = "response", targetNamespace = "http://nextlabs.com/destiny/interfaces/log/v3", partName = "response")
    @WebMethod
    public com.nextlabs.rms.services.cxf.destiny.types.log.v3.LogStatus logPolicyActivityV2(
            @WebParam(partName = "logs", name = "logs")
            java.lang.String logs
    ) throws UnauthorizedCallerFault, ServiceNotReadyFault;

    @WebResult(name = "response", targetNamespace = "http://nextlabs.com/destiny/interfaces/log/v3", partName = "response")
    @WebMethod
    public com.nextlabs.rms.services.cxf.destiny.types.log.v3.LogStatus logPolicyAssistant(
            @WebParam(partName = "logs", name = "logs")
            java.lang.String logs
    ) throws UnauthorizedCallerFault, ServiceNotReadyFault;

    @WebResult(name = "response", targetNamespace = "http://nextlabs.com/destiny/interfaces/log/v3", partName = "response")
    @WebMethod
    public com.nextlabs.rms.services.cxf.destiny.types.log.v3.LogStatus logTrackingV3(
            @WebParam(partName = "logs", name = "logs")
            java.lang.String logs
    ) throws UnauthorizedCallerFault, ServiceNotReadyFault;

    @WebResult(name = "response", targetNamespace = "http://nextlabs.com/destiny/interfaces/log/v3", partName = "response")
    @WebMethod
    public com.nextlabs.rms.services.cxf.destiny.types.log.v3.LogStatus logTracking(
            @WebParam(partName = "logs", name = "logs")
            java.lang.String logs
    ) throws UnauthorizedCallerFault, ServiceNotReadyFault;
}